### ISSUE TITLE
Consistent return type for getGraphIdsInCorpus(), getGraphIdsWithParticipant()

### ISSUE THREAD

**Issue by djvill** [nzilbb/labbcat-R#11]
If there are _n_ matches and _n_ > 0, `getGraphIdsInCorpus()` and `getGraphIdsWithParticipant()` return length-_n_ character vectors. However, if _n_ = 0, these functions return length-_n_ lists. Ideally, if _n_ = 0, these functions would return length-0 character vectors (i.e., `character(0L)`) to make return types consistent.

**Comment by robertfromont** [comment]
This change will be released in version 1.2-0
