### ISSUE TITLE
Sample code with httr::GET() is incomplete

### ISSUE THREAD

**Issue by djvill** [nzilbb/labbcat-R#23]
The sample code for using `httr::GET()` to access media references an object `labbcat` that hasn't been defined: https://github.com/nzilbb/labbcat-R/blob/77ca7f03f7c3336ab8dc9f700271f1ada25c1c4c/README.md?plain=1#L123

**Comment by robertfromont** [comment]
I've updated the README to reflect changes in version 1.2-0
