### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by robertfromont** [nzilbb/labbcat-R#6]
To be able to do 'everything' from within R, there needs to be a way of conducting searches, 
something like:

```
results <- labbcat.search(labbcat, "segments.label MATCHES 'I'", participants=participant.list)
```

How the search language might work (i.e. the "segments.label MATCHES 'I'" part), I'm not sure about yet.

**Comment by robertfromont** [comment]
Options:

#### SQL-like

SQL is a very established query language for relational databases. The query language we use for search could be designed to look similar to SQL:

```
results <- labbcat.search(labbcat, paste(
              "word.label = 'the'",
              "AND nextWord = word.next()",
              "AND nextWord.my('pos').label = 'N'",
              "AND nextWord.first('phone').label MATCHES '[aeiou]'"),
               participants=participant.list)
```

#### R-like

...or we could make it look a bit like R:

```
results <- labbcat.search(labbcat, paste(
              'word$label == "the"',
              '& my("pos", next(word))$label == "N"',
              '& grepl("[aeiou]" , first("phone", next(word))$label)"),
               participants=participant.list)
```

#### EQL

Emu already has a query language (EMU-SDMS Query Language – Winkelmann et al. (2016)), we could just implement that:

```
results <- labbcat.search(labbcat, paste(
              "[word = the ->",
              "[Text =~ .*",
              " ^pos = N",
              " ^phone =~ [aeiou] & Start(word, phone) = 1]"),
              participants=participant.list)
```

#### CQL

There's alread a Corpus Query Language designed for text corpora (Christ & Schulze (1994)), we could just implement that:

```
results <- labbcat.search(labbcat,
              '"the" [ pron="[aeiou]" first <pos="N"> ]',
              participants=participant.list)
```

#### FQL

There's a software project called "FoLiA" (Format for Linguistic Annotation), which as a query language called FQL, which we implement:

```
results <- labbcat.search(labbcat, paste(
              'SELECT w',
              'WHERE (text = "the" IN s AND',
              '  NEXT w WHERE (pos HAS class == "N"',
              '                AND phoneme MATCHES "[aeiou].*"))'),
              participants=participant.list)
```

#### AGQL

Bird et al. (the inventors of the Annotation Graph framework that LaBB-CAT uses) also designed a query language for it, which we could implement:

```
results <- labbcat.search(labbcat, paste(
              '[:"the"].[id: nextWord]       <- "word"',
              '[:"N", tags(nextWord)]        <- "pos"',
              '[:/[aeiou]/, first(nextWord)] <- "phone"', sep='\n'),
              participants=participant.list)
```

#### Object

A complex named-list object could be passed, which replicates the structure of the search matrix form in the LaBB-CAT browser UI.

**Comment by djvill** [comment]
Here's my idea for an more R-native solution: nested lists. Many R users will have encountered this type of structure for complex specifications, such as the `axes` argument in `effects:::plot.eff()`: https://cran.r-project.org/web/packages/effects/effects.pdf.

Implemented in this package, this could take on a few versions (depending on whether you want to make missings explicit or implicit, how you want to handle defaults, etc.). Here's an option with explicit missings:
```
results <- labbcat.search(labbcat, 
                          word = list(
                            orthography = list(match = "the"),
                            pos = NA,
                            phone = NA),
                          next_word = list(
                            orthography = NA,
                            pos = list(match = "N"),
                            phone = list(match = "[aeiou]")
                          ))
```

The real power in the nested lists is how extendible they are. So for example, the user could add a `not = TRUE` element to negate the pattern, Number layers could take `min` and `max`, etc.

And since the most common use case is a single string match to each layer, we could include the option of passing a string (e.g., `orthography = "the"`) as a shortcut to `orthography = list(match = "the")`; an in-the-wild example is `effects::predictorEffect()`'s `xlevels` argument ("it may either a single number specifying the number of evenly-spaced values (the default 5) to which each conditioning predictor is to be set, or it may be a list with named for the predictors giving the number of values or a vector of to which each conditioning predictor is to be set").

**Comment by robertfromont** [comment]
Looks good.
Probably the NA elements could be just omitted, actually.  And maybe collapse `word` and `next_word` into a vector?  So something like:
```
results <- labbcat.search(labbcat, c(
                          list(orthography = list(match = "the")), 
                          list(pos = list(match = "N"), phone = list(match = "[aeiou]"))
                          ))
```

Does that make sense?

**Comment by djvill** [comment]
Yeah, I think leaving the NAs implicit is good. Actually, NA or NULL could be reserved for finding empty annotations (i.e., what "not .+" does in the GUI).

I like the collapsed structure, too. And you potentially could take it one step further to replicate the linear logic represented in the GUI search panel:
```
results <- labbcat.search(labbcat, list(
                          "anything",
                          list(orthography = list(match = "the")), 
                          "1 word later",
                          list(pos = list(match = "N"), phone = list(match = "[aeiou]")),
                          "turn end"
                          ))
```
That might a bit complex to write in a usable fashion, though. The big list would have to be checked pretty strictly for structure (odd number of elements at level 1, the even-numbered level 1 elements are all lists, etc.), and it's probably bad practice to sprinkle required 'arguments' (here, level 1 list elements) that have typical defaults (e.g., "immediately") amongst those that will vary more widely (the layer specifications). Perhaps this argues for different syntax or even different functions for searches across 1 word versus 2+ words? A precedent for that is the base `*apply` family, where one function vectorizes over a single list (`lapply()`) and another vectorizes over multiple lists (`mapply()`).

**Comment by robertfromont** [comment]
Another option, as you suggest, would be to implement a [Shiny Gadget](https://shiny.rstudio.com/articles/gadgets.html).

**Comment by robertfromont** [comment]
Ok, so the forthcoming implementation will look like this:
```
# all words starting with "ps..."
# (abbreviated structure)
results <- getMatches(labbcat.url, list(orthography = "ps.*"))

# the word 'the' followed immediately or with one intervening word by
# a hapax legomenon (word with a frequency of 1) that doesn't start with a vowel
# (full structure, replicating the LaBB-CAT GUI's 'search matrix')
results <- getMatches(labbcat.url, list(columns = list(
     list(layers = list(
            orthography = list(pattern = "the")),
          adj = 2),
     list(layers = list(
            phonemes = list(not = TRUE, pattern = "[cCEFHiIPqQuUV0123456789~#\\{\\$@].*"),
            frequency = list(max = "2"))))))
```

**Comment by robertfromont** [comment]
The function definition will be:

`getMatches(labbcat.url, pattern, participantId=NULL, main.participant=TRUE, words.context=0, no.progress=FALSE)`

Formally, the pattern should be a named list that replicates the structure of the
    'search matrix' in the LaBB-CAT browser interface, with one element called
    "columns", containing a named list for each column.

Each element in the "columns" named list contains an element named "layers", whose
    value is a named list for patterns to match on each layer, and optionally an
    element named "adj", whose value is a number representing the maximum distance, in
    tokens, between this column and the next column - if "adj" is not specified, the
    value defaults to 1, so tokens are contiguous.

Each element in the "layers" named list is named after the layer it matches, and the
    value is a named list with the following possible elements:
- `pattern` A regular expression to match against the label
- `min` An inclusive minimum numeric value for the label
- `max` An exclusive maximum numeric value for the label
- `not` TRUE to negate the match
- `anchorStart` TRUE to anchor to the start of the annotation on this layer
    (i.e. the matching word token will be the first at/after the start of the matching
    annotation on this layer)
- `anchorEnd` TRUE to anchor to the end of the annotation on this layer
    (i.e. the matching word token will be the last before/at the end of the matching
    annotation on this layer)
- `target` TRUE to make this layer the target of the search; the results will
    contain one row for each match on the target layer

For ease of use, the function will also accept the following abbreviated forms:
```
## a single list representing a 'one column' search, 
## and string values, representing regular expression pattern matching
pattern <- list(orthography = "ps.*")

## a list containing the columns (adj defaults to 1, so matching tokens are contiguous)...
pattern <- list(
    list(orthography = "the"),
    list(phonemes = list(not = TRUE, pattern = "[cCEFHiIPqQuUV0123456789~#\\{\\$@].*"),
         frequency = list(max = "2")))
```

**Comment by robertfromont** [comment]
The data frame that's returned contains columns that can be used as parameters for other functions like `getAnnotationLabels`, `getSoundFragments`, and `getFragments`
